#!/bin/sh
# [Gedit Tool]
# Applicability=all
# Shortcut=<Primary><Shift>r
# Save-files=document
# Name=run-emulator
# Input=document
# Output=output-panel
# Languages=assembler (mc88110)

if [ -e ${GEDIT_CURRENT_DOCUMENT_NAME%.asm}.bin ]; then
    echo "Ejecutando emulador..."
    xterm -e "em88110 -c serie ${GEDIT_CURRENT_DOCUMENT_NAME%.asm}.bin" &
else
    err=$( 88110e -o ${GEDIT_CURRENT_DOCUMENT_NAME%.asm}.bin $GEDIT_CURRENT_DOCUMENT_NAME 2>&1 )
    echo $err

    linenum=$( echo $err | grep ERROR | grep -oP '\(\K\d+(?=\))' 2>&1 )
    if [ -n "$linenum" ]; then
        line=$(awk 'NR=='$linenum $GEDIT_CURRENT_DOCUMENT_NAME)
        echo "\n$linenum --> $line"
    fi

fi
